# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-08 01:04
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sentinel1_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
                ('url_download', models.CharField(blank=True, max_length=500, null=True)),
                ('url_checksum', models.CharField(blank=True, max_length=500, null=True)),
                ('instrument', models.CharField(blank=True, max_length=250, null=True)),
                ('product_type', models.CharField(blank=True, max_length=250, null=True)),
                ('sensor_operational_mode', models.CharField(blank=True, max_length=250, null=True)),
                ('sensing_date', models.DateTimeField(null=True)),
                ('ingestion_date', models.DateTimeField(null=True)),
                ('orbit_number', models.CharField(blank=True, max_length=250, null=True)),
                ('relative_orbit_number', models.CharField(blank=True, max_length=250, null=True)),
                ('pass_direction', models.CharField(blank=True, max_length=250, null=True)),
                ('wkt_footprint', models.CharField(blank=True, max_length=10000, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('polarization', models.CharField(blank=True, max_length=250, null=True)),
                ('swath', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('source2', models.CharField(blank=True, max_length=250, null=True)),
                ('score', models.IntegerField(null=True)),
                ('geom_footprint', django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326)),
            ],
        ),
    ]
