# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-08 01:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='hubs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hubname', models.CharField(blank=True, max_length=250, null=True)),
                ('hublink', models.CharField(blank=True, max_length=250, null=True)),
                ('hubscore', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='hubs_credentials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.hubs')),
            ],
        ),
        migrations.CreateModel(
            name='hubs_lastaccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accessdate', models.DateField(blank=True, null=True)),
                ('hubid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.hubs')),
            ],
        ),
        migrations.CreateModel(
            name='sentinel1_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
                ('url_download', models.CharField(blank=True, max_length=500, null=True)),
                ('url_checksum', models.CharField(blank=True, max_length=500, null=True)),
                ('instrument', models.CharField(blank=True, max_length=250, null=True)),
                ('product_type', models.CharField(blank=True, max_length=250, null=True)),
                ('sensor_operational_mode', models.CharField(blank=True, max_length=250, null=True)),
                ('sensing_date', models.DateTimeField(null=True)),
                ('ingestion_date', models.DateTimeField(null=True)),
                ('orbit_number', models.CharField(blank=True, max_length=250, null=True)),
                ('relative_orbit_number', models.CharField(blank=True, max_length=250, null=True)),
                ('pass_direction', models.CharField(blank=True, max_length=250, null=True)),
                ('wkt_footprint', models.CharField(blank=True, max_length=10000, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('polarization', models.CharField(blank=True, max_length=250, null=True)),
                ('swath', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sentinel2_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
                ('url_download', models.CharField(blank=True, max_length=500, null=True)),
                ('url_checksum', models.CharField(blank=True, max_length=500, null=True)),
                ('instrument', models.CharField(blank=True, max_length=250, null=True)),
                ('product_type', models.CharField(blank=True, max_length=250, null=True)),
                ('cloud_coverage', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('sensing_date', models.DateTimeField(null=True)),
                ('ingestion_date', models.DateTimeField(null=True)),
                ('orbit_number', models.CharField(blank=True, max_length=250, null=True)),
                ('relative_orbit_number', models.CharField(blank=True, max_length=250, null=True)),
                ('pass_direction', models.CharField(blank=True, max_length=250, null=True)),
                ('wkt_footprint', models.CharField(blank=True, max_length=10000, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('score', models.IntegerField(null=True)),
                ('tile_name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sentinel3_Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.CharField(max_length=500)),
                ('identifier', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=500)),
                ('url_download', models.CharField(blank=True, max_length=500, null=True)),
                ('url_checksum', models.CharField(blank=True, max_length=500, null=True)),
                ('instrument', models.CharField(blank=True, max_length=250, null=True)),
                ('product_type', models.CharField(blank=True, max_length=250, null=True)),
                ('product_class', models.CharField(blank=True, max_length=250, null=True)),
                ('sensor_operational_mode', models.CharField(blank=True, max_length=250, null=True)),
                ('sensing_date', models.DateTimeField(null=True)),
                ('ingestion_date', models.DateTimeField(null=True)),
                ('timeliness', models.CharField(blank=True, max_length=200, null=True)),
                ('procfacilityname', models.CharField(blank=True, max_length=250, null=True)),
                ('procfacilityorg', models.CharField(blank=True, max_length=200, null=True)),
                ('orbit_number', models.CharField(blank=True, max_length=250, null=True)),
                ('relative_orbit_number', models.CharField(blank=True, max_length=250, null=True)),
                ('pass_direction', models.CharField(blank=True, max_length=250, null=True)),
                ('wkt_footprint', models.CharField(blank=True, max_length=10000, null=True)),
                ('size', models.CharField(blank=True, max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=250, null=True)),
                ('score', models.IntegerField(null=True)),
            ],
        ),
    ]
