# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-09 10:01
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0003_auto_20190209_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentinel1_products',
            name='geom_footprint',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='sentinel2_products',
            name='geom_footprint',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='sentinel3_products',
            name='geom_footprint',
            field=django.contrib.gis.db.models.fields.PolygonField(blank=True, null=True, srid=4326),
        ),
    ]
