# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-10 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0004_auto_20190209_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubs_lastaccess',
            name='accessdate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
