# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-11 21:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0005_auto_20190210_1149'),
    ]

    operations = [
        migrations.AddField(
            model_name='hubs_lastaccess',
            name='product',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
