# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-16 18:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0006_hubs_lastaccess_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentinel2_products',
            name='geom_footprint2',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=4326),
        ),
    ]
