# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-02-19 06:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0008_auto_20190217_0900'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sentinel1_products',
            name='geom_footprint',
        ),
    ]
