# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-02 22:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0013_sentinel1_products_source2'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentinel2_products',
            name='source2',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='harvest.hubs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sentinel1_products',
            name='source2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='harvest.hubs'),
        ),
    ]
