# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-03-05 20:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0014_auto_20190302_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentinel1_products',
            name='quicklook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sentinel2_products',
            name='quicklook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sentinel3_products',
            name='quicklook',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
